image: node:latest

stages:
  - build
  - publish

cache:
  key: build-cache
  paths:
    - node_modules/
    - dist/
    - .npmrc
    - .yarn
  policy: push

build:
  stage: build
  only:
    - tags
  before_script:
    - echo "@gethenryco:registry=https://gitlab.com/api/v4/packages/npm/" >> .npmrc
    - echo "'//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken'="${CI_JOB_TOKEN}"" >> .npmrc
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn build

publish:
  stage: publish
  only:
    - tags
  script:
    - yarn version --patch --no-git-tag-version
    - yarn publish
